version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z
    ports:
      - "5432"
  docapp:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/home/
    ports:
      - "3000:3000"
    depends_on:
      - db
